/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register-admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register Admin
         * @description Crée un compte administrateur.
         *
         *     Endpoint de bootstrap : ne requiert pas d'authentification préalable, mais
         *     exige la clé secrète SuperAdmin (`secret_key`) définie dans la configuration
         *     (`SUPERADMIN_SECRET_KEY`).
         */
        post: operations["register_admin_api_v1_auth_register_admin_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Students */
        get: operations["list_students_api_v1_users_students_get"];
        put?: never;
        /** Create Student */
        post: operations["create_student_api_v1_users_students_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/students/{student_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Student */
        get: operations["get_student_api_v1_users_students__student_id__get"];
        put?: never;
        post?: never;
        /** Delete Student */
        delete: operations["delete_student_api_v1_users_students__student_id__delete"];
        options?: never;
        head?: never;
        /** Update Student */
        patch: operations["update_student_api_v1_users_students__student_id__patch"];
        trace?: never;
    };
    "/api/v1/users/teachers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Teachers */
        get: operations["list_teachers_api_v1_users_teachers_get"];
        put?: never;
        /** Create Teacher */
        post: operations["create_teacher_api_v1_users_teachers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/teachers/{teacher_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Teacher */
        get: operations["get_teacher_api_v1_users_teachers__teacher_id__get"];
        put?: never;
        post?: never;
        /** Delete Teacher */
        delete: operations["delete_teacher_api_v1_users_teachers__teacher_id__delete"];
        options?: never;
        head?: never;
        /** Update Teacher */
        patch: operations["update_teacher_api_v1_users_teachers__teacher_id__patch"];
        trace?: never;
    };
    "/api/v1/vms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Vms */
        get: operations["list_vms_api_v1_vms_get"];
        put?: never;
        /** Create Vm */
        post: operations["create_vm_api_v1_vms_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vms/{vm_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Vm */
        get: operations["get_vm_api_v1_vms__vm_id__get"];
        put?: never;
        post?: never;
        /** Delete Vm */
        delete: operations["delete_vm_api_v1_vms__vm_id__delete"];
        options?: never;
        head?: never;
        /** Update Vm */
        patch: operations["update_vm_api_v1_vms__vm_id__patch"];
        trace?: never;
    };
    "/api/v1/vms/{vm_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Vm */
        post: operations["start_vm_api_v1_vms__vm_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vms/{vm_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop Vm */
        post: operations["stop_vm_api_v1_vms__vm_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vms/{vm_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause Vm */
        post: operations["pause_vm_api_v1_vms__vm_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requetes/create-vm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Vm Request */
        post: operations["create_vm_request_api_v1_requetes_create_vm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requetes/delete-vm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete Vm Request */
        post: operations["delete_vm_request_api_v1_requetes_delete_vm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requetes/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Account Request */
        post: operations["account_request_api_v1_requetes_account_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requetes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Requetes */
        get: operations["list_requetes_api_v1_requetes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requetes/{requete_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Requete */
        get: operations["get_requete_api_v1_requetes__requete_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requetes/{requete_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Requete */
        post: operations["approve_requete_api_v1_requetes__requete_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requetes/{requete_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Requete */
        post: operations["reject_requete_api_v1_requetes__requete_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/publications/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Public Publications */
        get: operations["list_public_publications_api_v1_publications_public_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/publications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Publications */
        get: operations["list_publications_api_v1_publications_get"];
        put?: never;
        /** Create Publication */
        post: operations["create_publication_api_v1_publications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/publications/{publication_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Publication */
        get: operations["get_publication_api_v1_publications__publication_id__get"];
        put?: never;
        post?: never;
        /** Delete Publication */
        delete: operations["delete_publication_api_v1_publications__publication_id__delete"];
        options?: never;
        head?: never;
        /** Update Publication */
        patch: operations["update_publication_api_v1_publications__publication_id__patch"];
        trace?: never;
    };
    "/api/v1/dns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List All Dns
         * @description Liste toutes les entrées DNS du système (admin uniquement).
         */
        get: operations["list_all_dns_api_v1_dns_get"];
        put?: never;
        /**
         * Create Dns
         * @description Crée une nouvelle entrée DNS pour une VM.
         *
         *     - Le hostname doit être un FQDN valide (ex: `api.projet.dc.enspy.cm`).
         *     - Un hostname ne peut être attribué qu'à une seule VM à la fois.
         *     - Seul le propriétaire de la VM (ou un admin) peut créer une entrée DNS.
         */
        post: operations["create_dns_api_v1_dns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dns/vms/{vm_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Dns For Vm
         * @description Liste toutes les entrées DNS associées à une VM donnée.
         */
        get: operations["list_dns_for_vm_api_v1_dns_vms__vm_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dns/{dns_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dns
         * @description Récupère une entrée DNS par son identifiant.
         */
        get: operations["get_dns_api_v1_dns__dns_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Dns
         * @description Supprime une entrée DNS.
         */
        delete: operations["delete_dns_api_v1_dns__dns_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Dns
         * @description Modifie le hostname d'une entrée DNS existante.
         */
        patch: operations["update_dns_api_v1_dns__dns_id__patch"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdminCreate
         * @description Création d'un compte administrateur, protégée par la clé secrète SuperAdmin.
         */
        AdminCreate: {
            /** Username */
            username: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /**
             * Role
             * @default Admin
             * @enum {string}
             */
            role: "Admin" | "SuperAdmin";
            /** Secret Key */
            secret_key: string;
        };
        /** ApproveBody */
        ApproveBody: {
            /**
             * Ssh Public Key
             * @default
             */
            ssh_public_key: string;
        };
        /**
         * DNSEntryCreate
         * @description Payload pour créer une entrée DNS.
         */
        DNSEntryCreate: {
            /** Hostname */
            hostname: string;
            /** Vm Id */
            vm_id: number;
        };
        /**
         * DNSEntryRead
         * @description Réponse renvoyée au client, inclut les champs générés par la BDD.
         */
        DNSEntryRead: {
            /** Hostname */
            hostname: string;
            /** Vm Id */
            vm_id: number;
            /** Id */
            id: number;
            /** Ip Address */
            ip_address?: string | null;
        };
        /**
         * DNSEntryUpdate
         * @description Payload partiel pour modifier une entrée DNS.
         */
        DNSEntryUpdate: {
            /** Hostname */
            hostname?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** PaginatedResponse[DNSEntryRead] */
        PaginatedResponse_DNSEntryRead_: {
            /** Items */
            items: components["schemas"]["DNSEntryRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /** PaginatedResponse[PublicationRead] */
        PaginatedResponse_PublicationRead_: {
            /** Items */
            items: components["schemas"]["PublicationRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /** PaginatedResponse[StudentRead] */
        PaginatedResponse_StudentRead_: {
            /** Items */
            items: components["schemas"]["StudentRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /** PaginatedResponse[TeacherRead] */
        PaginatedResponse_TeacherRead_: {
            /** Items */
            items: components["schemas"]["TeacherRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /** PaginatedResponse[Union[RCreateVMRead, RDeleteVMRead, RAccountRead]] */
        PaginatedResponse_Union_RCreateVMRead__RDeleteVMRead__RAccountRead__: {
            /** Items */
            items: (components["schemas"]["RCreateVMRead"] | components["schemas"]["RDeleteVMRead"] | components["schemas"]["RAccountRead"])[];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /** PaginatedResponse[VMRead] */
        PaginatedResponse_VMRead_: {
            /** Items */
            items: components["schemas"]["VMRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /** PublicationCreate */
        PublicationCreate: {
            /** Nom */
            nom: string;
            /**
             * Status
             * @default draft
             * @enum {string}
             */
            status: "draft" | "published" | "archived";
            /** Lien */
            lien?: string | null;
            /** Description */
            description?: string | null;
            /** Photo */
            photo?: string | null;
            /** User Id */
            user_id: number;
        };
        /** PublicationRead */
        PublicationRead: {
            /** Nom */
            nom: string;
            /**
             * Status
             * @default draft
             * @enum {string}
             */
            status: "draft" | "published" | "archived";
            /** Lien */
            lien?: string | null;
            /** Description */
            description?: string | null;
            /** Photo */
            photo?: string | null;
            /** Id */
            id: number;
            /** User Id */
            user_id: number;
        };
        /** PublicationUpdate */
        PublicationUpdate: {
            /** Nom */
            nom?: string | null;
            /** Lien */
            lien?: string | null;
            /** Description */
            description?: string | null;
            /** Photo */
            photo?: string | null;
            /** Status */
            status?: ("draft" | "published" | "archived") | null;
        };
        /** RAccountCreate */
        RAccountCreate: {
            /** Object */
            object: string;
            /** Content */
            content?: string | null;
            /** Teacher Id */
            teacher_id: number;
            /** Nom */
            nom: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Justification */
            justification?: string | null;
            /** Matricule */
            matricule?: string | null;
            /** Organisation */
            organisation?: string | null;
        };
        /** RAccountRead */
        RAccountRead: {
            /** Object */
            object: string;
            /** Content */
            content?: string | null;
            /** Student Id */
            student_id: number;
            /** Teacher Id */
            teacher_id: number;
            /** Id */
            id: number;
            /**
             * Type
             * @constant
             */
            type: "r_account";
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "validated" | "rejected";
            /** Nom */
            nom: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Justification */
            justification?: string | null;
            /** Matricule */
            matricule?: string | null;
            /** Organisation */
            organisation?: string | null;
        };
        /** RCreateVMCreate */
        RCreateVMCreate: {
            /** Object */
            object: string;
            /** Content */
            content?: string | null;
            /** Teacher Id */
            teacher_id: number;
            /** Size Rom */
            size_rom: number;
            /** Size Ram */
            size_ram: number;
            /** Os */
            os: string;
        };
        /** RCreateVMRead */
        RCreateVMRead: {
            /** Object */
            object: string;
            /** Content */
            content?: string | null;
            /** Student Id */
            student_id: number;
            /** Teacher Id */
            teacher_id: number;
            /** Id */
            id: number;
            /**
             * Type
             * @constant
             */
            type: "r_create_vm";
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "validated" | "rejected";
            /** Size Rom */
            size_rom: number;
            /** Size Ram */
            size_ram: number;
            /** Os */
            os: string;
        };
        /** RDeleteVMCreate */
        RDeleteVMCreate: {
            /** Object */
            object: string;
            /** Content */
            content?: string | null;
            /** Teacher Id */
            teacher_id: number;
            /** Vm Id */
            vm_id: number;
        };
        /** RDeleteVMRead */
        RDeleteVMRead: {
            /** Object */
            object: string;
            /** Content */
            content?: string | null;
            /** Student Id */
            student_id: number;
            /** Teacher Id */
            teacher_id: number;
            /** Id */
            id: number;
            /**
             * Type
             * @constant
             */
            type: "r_delete_vm";
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "validated" | "rejected";
            /** Vm Id */
            vm_id: number;
        };
        /** StudentCreate */
        StudentCreate: {
            /** Username */
            username: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Matricule */
            matricule: string;
            /** Level */
            level: string;
            /** Departement */
            departement: string;
        };
        /** StudentRead */
        StudentRead: {
            /** Username */
            username: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Id */
            id: number;
            /**
             * Type
             * @constant
             */
            type: "student";
            /** Matricule */
            matricule: string;
            /** Level */
            level: string;
            /** Departement */
            departement: string;
        };
        /** StudentUpdate */
        StudentUpdate: {
            /** Username */
            username?: string | null;
            /** Email */
            email?: string | null;
            /** Level */
            level?: string | null;
            /** Departement */
            departement?: string | null;
        };
        /** TeacherCreate */
        TeacherCreate: {
            /** Username */
            username: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Role */
            role: string;
        };
        /** TeacherRead */
        TeacherRead: {
            /** Username */
            username: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Id */
            id: number;
            /**
             * Type
             * @constant
             */
            type: "teacher";
            /** Role */
            role: string;
        };
        /** TeacherUpdate */
        TeacherUpdate: {
            /** Username */
            username?: string | null;
            /** Email */
            email?: string | null;
            /** Role */
            role?: string | null;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** VMCreate */
        VMCreate: {
            /** Size Rom */
            size_rom: number;
            /** Size Ram */
            size_ram: number;
            /** N Cpu */
            n_cpu: number;
            /**
             * Status
             * @default stopped
             * @enum {string}
             */
            status: "up" | "waiting" | "stopped";
            /** Iso */
            iso?: string | null;
            /** Ip Address */
            ip_address?: string | null;
            /** Id Proxmox */
            id_proxmox?: number | null;
            /** Node */
            node?: string | null;
            /** Iso Image */
            iso_image?: string | null;
            /** Ssh Public Key */
            ssh_public_key?: string | null;
            /** User Id */
            user_id: number;
        };
        /** VMRead */
        VMRead: {
            /** Size Rom */
            size_rom: number;
            /** Size Ram */
            size_ram: number;
            /** N Cpu */
            n_cpu: number;
            /**
             * Status
             * @default stopped
             * @enum {string}
             */
            status: "up" | "waiting" | "stopped";
            /** Iso */
            iso?: string | null;
            /** Ip Address */
            ip_address?: string | null;
            /** Id Proxmox */
            id_proxmox?: number | null;
            /** Node */
            node?: string | null;
            /** Iso Image */
            iso_image?: string | null;
            /** Ssh Public Key */
            ssh_public_key?: string | null;
            /** Id */
            id: number;
            /** User Id */
            user_id: number;
            /** Date Stop At */
            date_stop_at?: string | null;
        };
        /** VMUpdate */
        VMUpdate: {
            /** Size Rom */
            size_rom?: number | null;
            /** Size Ram */
            size_ram?: number | null;
            /** N Cpu */
            n_cpu?: number | null;
            /** Status */
            status?: string | null;
            /** Iso */
            iso?: string | null;
            /** Ip Address */
            ip_address?: string | null;
            /** Id Proxmox */
            id_proxmox?: number | null;
            /** Node */
            node?: string | null;
            /** Iso Image */
            iso_image?: string | null;
            /** Ssh Public Key */
            ssh_public_key?: string | null;
            /** Date Stop At */
            date_stop_at?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_admin_api_v1_auth_register_admin_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeacherRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentRead"] | components["schemas"]["TeacherRead"] | {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_students_api_v1_users_students_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_StudentRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_student_api_v1_users_students_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_student_api_v1_users_students__student_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_student_api_v1_users_students__student_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_student_api_v1_users_students__student_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_teachers_api_v1_users_teachers_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_TeacherRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_teacher_api_v1_users_teachers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeacherCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeacherRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_teacher_api_v1_users_teachers__teacher_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teacher_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeacherRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_teacher_api_v1_users_teachers__teacher_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teacher_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_teacher_api_v1_users_teachers__teacher_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teacher_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeacherUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeacherRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_vms_api_v1_vms_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_VMRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_vm_api_v1_vms_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VMCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VMRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_vm_api_v1_vms__vm_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vm_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VMRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_vm_api_v1_vms__vm_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vm_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_vm_api_v1_vms__vm_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vm_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VMUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VMRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_vm_api_v1_vms__vm_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vm_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VMRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_vm_api_v1_vms__vm_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vm_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VMRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_vm_api_v1_vms__vm_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vm_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VMRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_vm_request_api_v1_requetes_create_vm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RCreateVMCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RCreateVMRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_vm_request_api_v1_requetes_delete_vm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RDeleteVMCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RDeleteVMRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    account_request_api_v1_requetes_account_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RAccountCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RAccountRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_requetes_api_v1_requetes_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_Union_RCreateVMRead__RDeleteVMRead__RAccountRead__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_requete_api_v1_requetes__requete_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requete_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_requete_api_v1_requetes__requete_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requete_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_requete_api_v1_requetes__requete_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requete_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_public_publications_api_v1_publications_public_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_PublicationRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_publications_api_v1_publications_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_PublicationRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_publication_api_v1_publications_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublicationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_publication_api_v1_publications__publication_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publication_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_publication_api_v1_publications__publication_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publication_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_publication_api_v1_publications__publication_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publication_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublicationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_dns_api_v1_dns_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_DNSEntryRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_dns_api_v1_dns_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DNSEntryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DNSEntryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_dns_for_vm_api_v1_dns_vms__vm_id__get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                vm_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_DNSEntryRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dns_api_v1_dns__dns_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dns_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DNSEntryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_dns_api_v1_dns__dns_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dns_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_dns_api_v1_dns__dns_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dns_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DNSEntryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DNSEntryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
